# Generated by Django 2.0.7 on 2021-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('cell_number', models.CharField(max_length=10)),
                ('client_email', models.TextField()),
                ('client_ID', models.CharField(max_length=9)),
            ],
        ),
    ]
