# Generated by Django 2.0.7 on 2021-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_new',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
