# Generated by Django 2.0.7 on 2021-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0002_client_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='request_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=False, max_length=128),
        ),
    ]
