# Generated by Django 2.0.7 on 2021-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0003_auto_20211005_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
