# Generated by Django 2.0.7 on 2021-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_auto_20211005_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
    ]
