# Generated by Django 2.0.7 on 2021-10-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0006_auto_20211006_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='request_message',
            field=models.TextField(null=True),
        ),
    ]
