# Generated by Django 2.0.7 on 2021-10-06 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0007_auto_20211006_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ID',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('/\\D/')]),
        ),
    ]
