# Generated by Django 2.0.7 on 2021-10-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0008_auto_20211006_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='request_message',
        ),
    ]
