# Generated by Django 2.0.7 on 2021-10-06 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0011_auto_20211006_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='request_message',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=None),
        ),
    ]
