# Generated by Django 2.0.7 on 2021-10-06 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0013_auto_20211006_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ID',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('\\d')]),
        ),
    ]
