# Generated by Django 2.0.7 on 2021-10-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0015_auto_20211006_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='request_message',
        ),
    ]
