# Generated by Django 2.0.7 on 2021-10-06 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0017_client_request_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ID', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('\\d')])),
                ('request_msg', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='request_message',
        ),
    ]
