# Generated by Django 2.0.7 on 2021-10-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0020_client_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_files',
            name='requested_doc',
            field=models.FileField(upload_to=''),
        ),
    ]
