# Generated by Django 2.0.7 on 2021-10-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0021_auto_20211008_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Files',
            new_name='Files',
        ),
    ]
